jobovy/galpy

HISTORY.txt, doc/source/potential.rst, doc/source/reference/potential.rst, doc/source/reference/potential3mn.rst, galpy/orbit_src/integrateFullOrbit.py, galpy/orbit_src/integratePlanarOrbit.py, galpy/potential.py, galpy/potential_src/MN3ExponentialDiskPotential.py, nose/test_nemo.py, nose/test_orbit.py, nose/test_potential.py
=> Adds the 3MN potential of Smith et al. (2015)

.travis.yml, HISTORY.txt, doc/source/examples/galpyrc, doc/source/installation.rst, doc/source/whatsnew.rst, galpy/df_src/streamdf.py, galpy/orbit_src/FullOrbit.py, galpy/orbit_src/Orbit.py, galpy/orbit_src/OrbitTop.py, galpy/util/bovy_coords.py, galpy/util/config.py, nose/test_coords.py, nose/test_galpypaper.py, nose/test_orbit.py, nose/test_streamdf.py
This pull request adds support for using ``astropy.coordinates`` transformations, primarily to go from ``(ra,dec)`` to ``(l,b)``. Using astropy can be set by a configuration parameter (default: True), non-astropy is still supported and can use astropy to figure out the transformation for general epochs (incl. for the velocities).
Also fixes the way Galactocentric coordinates are computed, consistent with astropy.
=> Use astropy.coordinates for internal coordinate transformations

nose/test_scf.py
Added an extra test that should cover the three missed lines from 
[https://codecov.io/gh/jobovy/galpy/src/6037e50cfc1dbbbd74053ea6433ba30f947d6ad7/galpy/potential_src/SCFPotential.py](https://codecov.io/gh/jobovy/galpy/src/6037e50cfc1dbbbd74053ea6433ba30f947d6ad7/galpy/potential_src/SCFPotential.py)
Did not make any test to cover that last miss since roundoff isn't used(although it could in the future?).
=> Increased test coverage for SCFPotential: axisymmetric case

galpy/potential_src/potential_c_ext/SCFPotential.c
Replaced deprecated gsl_sf_legendre_Plm_array with gsl_sf_legendre_array_e for GSL v2.
Optimized axisymmetric case by using gsl_sf_legendre_Pl_array.
=> SCFPotential for v1 and v2 of GSL

doc/source/getting_started.rst
In v1.2 the order of parameters of the function evaluatezforce changed from (R,z,Pot) to (Pot,R,z)
=> Updated the order of function parameters

galpy/orbit_src/FullOrbit.py, galpy/orbit_src/RZOrbit.py, galpy/orbit_src/planarOrbit.py, nose/test_orbit.py
I noticed that the integration routines silently falls back to python methods when C methods are selected, and thought it'd be better to issue a warning of the change explicitly.
I think there are couple of other integration routines for e.g., planar orbits, but I submit this example to see if you think this is a good idea. (Although right now, the methods in classes default to C, and you are warned when C integrations are actually used..)
=> issue warning when integration method changes

galpy/potential_src/FerrersPotential.py, tests/test_potential.py
Hi Jo,
This is to fix #319. I think it was from a trivial mistake in rotating back xy/xz derivatives from bar-aligned to non-rotating frame. Please let me know if everything looks good.
```sh
galpy git/fix-ferrers-rzderiv
$git show
commit 4a50d2934bbc9bab15b6ddca893ac4f3e15552ac
Author: Semyeong Oh <semyeong.oh@gmail.com>
Date:   Wed Oct 18 14:38:55 2017 -0400
Fix trivial mistake in rotating back phixza, phiyza
diff --git a/galpy/potential_src/FerrersPotential.py b/galpy/potential_src/FerrersPotential.py
index e34f3cd..a4f4106 100644
--- a/galpy/potential_src/FerrersPotential.py
+++ b/galpy/potential_src/FerrersPotential.py
@@ -276,7 +276,7 @@ class FerrersPotential(Potential):
ang = self._omegab*t + self._pa
c, s = np.cos(ang), np.sin(ang)
phixz = c*phixza + s*phiyza
-        phiyz = …
```
=> Fix bug in FerrersPotential.Rzderiv

.appveyor.yml, doc/source/installation.rst, setup.py
Fix galpy with openmp compilation on Windows, performance tests:
```
from galpy.potential import MWPotential2014
from galpy.actionAngle import actionAngleAdiabatic
from galpy.orbit import Orbit
import numpy
aAA = actionAngleAdiabatic(pot=MWPotential2014, c=True)
ts = numpy.linspace(0., 100., 10001)
o = Orbit([1., 0.1, 1.1, 0., 0.05])
o.integrate(ts, MWPotential2014)
%timeit aAA(o.R(ts), o.vR(ts), o.vT(ts), o.z(ts), o.vz(ts))
```
**Win10 v1803 x64 py36 (4 cores 8 threads 4.2GHz)**
Compiled with OpenMP: 154 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Compiled without OpenMP: 945 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loop each)
And
```
from galpy.potential import MWPotential2014
from galpy.actionAngle import actionAngleStaeckel, estimateDeltaStaeckel …
```
=> Fix galpy with openmp compilation on Windows

setup.py
check `msvc` compiler exists and can be initialize on windows even if `gsl` is installed.
A PR for issue #348
=> Check compiler

HISTORY.txt, README.dev, doc/source/reference/potential.rst, doc/source/reference/potential1dtolinear.rst, galpy/orbit/integrateLinearOrbit.py, galpy/orbit/linearOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integrateLinearOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/potential/KGPotential.py, galpy/potential/Potential.py, galpy/potential/SpiralArmsPotential.py, galpy/potential/__init__.py, galpy/potential/potential_c_ext/KGPotential.c, galpy/potential/potential_c_ext/galpy_potentials.c, galpy/potential/potential_c_ext/galpy_potentials.h, galpy/potential/potential_c_ext/verticalPotential.c, galpy/potential/verticalPotential.py, tests/test_orbit.py, tests/test_potential.py, tests/test_quantity.py
This PR adds the general functionality to integrate ``linearOrbit`` instances in C and tests that this works for all currently available potentials.
=> Implement 1D orbit integration in C

galpy/util/bovy_rk.c, galpy/util/bovy_symplecticode.c, galpy/util/bovy_symplecticode.h
I have added the functionality to handle ctrl-c on windows
It works fine for Visual Studio 2017 15.9.2 on my Windows 10 v1809 x64 with Python 3.7 which leads to `KeyboardInterrupt: Orbit integration interrupted by CTRL-C (SIGINT)` on windows while pressing CTRL-C during integration with C code
=> Handle ctrl-c on windows too

HISTORY.txt, doc/source/getting_started.rst, doc/source/orbit.rst, doc/source/potential.rst, doc/source/reference/potential.rst, doc/source/reference/potential1dadd.rst, doc/source/reference/potential1dmul.rst, doc/source/reference/potential2dadd.rst, doc/source/reference/potential2dmul.rst, doc/source/reference/potentialadd.rst, doc/source/reference/potentialmul.rst, galpy/potential/ChandrasekharDynamicalFrictionForce.py, galpy/potential/Force.py, galpy/potential/linearPotential.py, galpy/potential/planarPotential.py, tests/test_potential.py
This PR adds the ability to combine Forces/Potentials/planarPotentials/linearPotentials by using the addition operator ``+``, e.g.,
```
from galpy.potential import PowerSphericalPotentialwCutoff, MiyamotoNagaiPotential, NFWPotential
bp= PowerSphericalPotentialwCutoff(alpha=1.8,rc=1.9/8.,normalize=0.05)
mp= MiyamotoNagaiPotential(a=3./8.,b=0.28/8.,normalize=.6)
np= NFWPotential(a=16/8.,normalize=.35)
MWPotential2014= bp+mp+np
```
to define ``MWPotential2014``. The addition operator simply creates lists of the input Potentials.
This PR also adds the ability to change a Force/Potential/planarPotential/linearPotential's amplitude by simply multiplying the instance by a number. So for instance:
```
MWPotential2014[2]*= 1.5
```
increases the mass of the NFW dark-matter halo by a factor of 1.5. …
=> Add Potential arithmetic

doc/source/installation.rst
I just realized the newer Anaconda for Windows migrated to PowerShell from CMD now so the compiling on Windows guide is not working straightforward. I have added an equivalent script for PowerShell so people can just copy and paste if using PowerShell.
I also tested to compile galpy with the new MSVC 2019 compiler and things seem fine.
=> PowerShell script in docs for Windows

galpy/orbit/Orbits.py
small change to Orbits such that Orbits may be fully subclassed.
Now __getitem__ will return an instance of child, not parent, class.
=> Allow Orbits to be subclassed 

galpy/potential/DehnenBarPotential.py
The calculation of smooth when t is an array is incorrect. indx=(t < self._tform) set smooth=0 for t < tform, but those values were being overwritten by indx=(t < self._tsteady). So the bar was growing before and after self._tform.
This edit should do the trick
=> Fixed indx in smooth so bar does not grow for t < t_form

__intelcompiler.py, doc/source/index.rst, doc/source/installation.rst, galpy/potential/DehnenSmoothWrapperPotential.py, setup.py
Last night I was just curious to compile galpy with Intel Compiler as I can get a free copy of Intel Compiler for personal educational use and googled some ways to compiled galpy with Intel Compiler. Moreover, as per free Intel Compiler license, I don't think I can distribute anything compiled with my free Intel Compiler but I guess it will be nice if anyone with the compiler can compile ``galpy`` to run faster.
**Don't merge it yet** as I will test it on the server later to see if the compilation command will work on Linux but at least it works on Windows. I just make this PR first to keep track the performance comparison I did on Windows. And I guess on Linux/MacOS one can specify `LDSHARED` and `CC` variable to compile with Intel Compiler? But it does not seems to work on Windows …
=> Enable galpy to be compiled with Intel Compiler

AUTHORS.txt, galpy/potential/Potential.py, galpy/potential/TwoPowerSphericalPotential.py, galpy/potential/planarPotential.py, galpy/potential/plotEscapecurve.py, galpy/potential/plotRotcurve.py
there are a lot of functions, like vcirc, that call time-dependent functions but do not themselves have a time parameter. I just went and found as many time-dependent functions as I could. in `galpy.potential` (and all functions that called those functions) and gave them time parameters.
=> add time dependences to Potential and related functions

AUTHORS.txt, RELEASE_CHECKLIST.md, galpy/potential/amuse.py, tests/test_amuse.py
A Potential instantiated with astropy quantitities has the `physical` flag set to true. The `galpy_profile` wrapper for amuse compatibility does all calculations without physical units. Normally this is not a problem as the galpy output is piped directly from galpy to. AMUSE,  but for `galpy_profile.get_gravity_at_point` the galpy output is first converted to cartesian coordinates and the units are adjusted. To prevent double conversion in the instances that galpy uses physical units, the `evaluateRforces`, `evaluatephiforces`, and `evaluatezforces` methods need to pass `use_physical=False`.
=> fixed amuse compatibility with Potentials instantiated with astropy quantities

galpy/orbit/Orbits.py
I refactored the JavaScript to improve orbits animation performance. Doing extend traces and restyling for all traces at once seems to improve quite a lot! At least animating all solar system planets together is smooth now!
Not sure what ``update_trace34``, ``update_trace56`` are doing but I updated them the same way as ``update_trace12`` and hope they work correctly, they are probably some way of animating orbits I don't know?
=> Improvement orbits animation performance

.appveyor.yml, .travis.yml, galpy/actionAngle/actionAngleAdiabatic_c.py, galpy/actionAngle/actionAngleStaeckel_c.py, galpy/actionAngle/actionAngleTorus_c.py, galpy/orbit/integrateFullOrbit.py, galpy/orbit/integrateLinearOrbit.py, galpy/orbit/integratePlanarOrbit.py, galpy/potential/interpRZPotential.py, galpy/util/bovy_rk.c, galpy/util/bovy_symplecticode.c, galpy/util/leung_dop853.c, setup.py, tests/orbitint4sigint.py, tests/test_orbit.py
Opening an explicit pull request for this, because it turned out to be somewhat non-trivial. Notes:
* Linux/Mac worked out of the box, 
* but coverage of the parts of the C code when orbit integration gets interrupted failed. Eventually traced this down to, I think, the fact that in Python 3.8 that KeyboardInterrupt actually properly interrupts the C code, leading to a -2 exit code (the one for SIGINT), and the ``abort`` of the C code that this causes makes it that ``gcov`` output is not recorded. I fixed this by explicitly flushing ``gcov`` outout with ``__gcov_flush()`` in the interrupt code, with pre-processor directives to only turn this on when compiling with ``--coverage``.
* For Windows, compilation worked fine, but the DLLs were no longer loaded because Python and ``ctypes`` in …
=> Add Python 3.8 support

.appveyor.yml, RELEASE_CHECKLIST.md, doc/source/conf.py, doc/source/installation.rst, galpy/__init__.py, setup.py
This PR adds to the AppVeyor ``.appveyor`` configuration file to build wheels for different Python versions for Windows each time the AppVeyor build runs. All wheels are built as part of the first job, so they can be accessed from that job's "Artifacts" page. At release, these wheels could be downloaded into the ``dist/`` directory and uploaded to PyPI.
=> Automatically build windows wheels using AppVeyor for different Python versions

doc/source/reference/bovycoords.rst, doc/source/reference/coordscyltospher.rst, doc/source/reference/coordscyltosphervec.rst, doc/source/reference/coordssphertocyl.rst, doc/source/reference/coordssphertocylvec.rst, doc/source/reference/orbit.rst, doc/source/reference/orbitsphvr.rst, doc/source/reference/orbittheta.rst, doc/source/reference/orbitvtheta.rst, galpy/orbit/Orbits.py, galpy/util/bovy_coords.py, tests/test_coords.py, tests/test_orbit.py
Add spherical coordinate methods to orbit.Orbit and cylindrical <--> spherical transformation methods to util.bovy_coords
=> Spherical coordinate support

galpy/df/sphericaldf.py, tests/test_sphericaldf.py
Uses start_indx to set minimum value of cml_pvr used to make 1D cumulative p(v|r) -> v_vesc interpolators. Ensures when the DF is negative or 0 for a non-zero v_vesc that the interpolator can properly initialize and be used to sample v_vesc.
=> Adds starting index to range of cml_pvr used to make interpolator

galpy/potential/Potential.py
first check its a Potential
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>
=> Don't flatten Potential instances

galpy/potential/TwoPowerSphericalPotential.py
Sorry for making two PRs, didnt realize I also needed Rzderiv in my previous one 😅
here's a code tidbit for testing it numerically
```
from galpy.potential import TwoPowerSphericalPotential
import numpy as np
pot = TwoPowerSphericalPotential()
assert np.abs(pot.Rzderiv(1, 0.5) + (pot.Rforce(1, 0.5+1E-8) - pot.Rforce(1, 0.5-1E-8)) / 2E-8 ) < 1E-8
assert np.abs(pot.Rzderiv(3, 0) + (pot.Rforce(3, 1E-8) - pot.Rforce(3, -1E-8)) / 2E-8 ) < 1E-8
```
=> Add _Rzderiv to TwoPowerSphericalPotential

galpy/df/constantbetadf.py, galpy/df/eddingtondf.py, galpy/df/osipkovmerrittdf.py, galpy/df/sphericaldf.py, tests/test_sphericaldf.py
Adds rmin to general spherical DFs, not potential-specific DFs (i.e. Hernquist or NFW variations). Also adds limited tests for rmin and rmax use in DFs.
=> Constantbetadf

HISTORY.txt, doc/source/reference/potential.rst, doc/source/reference/potentialphizderiv.rst, doc/source/reference/potentialphizderivs.rst, doc/source/reference/potentialrotateandtiltwrapper.rst, galpy/orbit/integrateFullOrbit.py, galpy/orbit/integratePlanarOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/potential/DehnenBarPotential.py, galpy/potential/EllipsoidalPotential.py, galpy/potential/FerrersPotential.py, galpy/potential/LogarithmicHaloPotential.py, galpy/potential/NumericalPotentialDerivativesMixin.py, galpy/potential/Potential.py, galpy/potential/RotateAndTiltWrapperPotential.py, galpy/potential/SpiralArmsPotential.py, galpy/potential/__init__.py, galpy/potential/planarPotential.py, galpy/potential/potential_c_ext/RotateAndTiltWrapperPotential.c, galpy/potential/potential_c_ext/galpy_potentials.h, galpy/potential/potential_c_ext/zvecAdjustmentWrapperPotential.c, galpy/potential/zvecAdjustmentWrapperPotential.py, galpy/util/bovy_coords.c, galpy/util/bovy_coords.h, tests/test_orbit.py, tests/test_potential.py, tests/test_quantity.py
I started having a go at implementing this wrapper potential which allows an adjustment to the z-axis of a potential. This will allow for potentials to be tilted around (in a similar way to the transformations currently allowed when using `EllipsoidalPotential` type potentials). Starting the PR to keep my momentum up!
The python implementation of the potential seems to be working as expected, but including the C code has given me some hiccups (which I think will cause the tests to fail!). I can't see why - but orbit integration in C doesn't seem to want to work. This is my first foray into C, so that might explain it.
I need to add testing of all the added things - once that's done, hopefully this should merge in easily...
=> Including a wrapper to allow the z-axis vector of a potential to be adjusted (e.g. inclined discs, tilted bar)

galpy/actionAngle/actionAngle.py, galpy/actionAngle/actionAngleIsochroneApprox.py
I think this issue affects both `actionAngleAdiabatic` and `actionAngleIsochroneApprox`
This works fine:
```python
from galpy.potential import MWPotential2014
from galpy.actionAngle import actionAngleAdiabatic
from galpy.orbit import Orbit
import numpy
aAA= actionAngleAdiabatic(pot=MWPotential2014)
ts=numpy.linspace(0.,100.,1001)
o= Orbit([1.,0.1,1.1,0.,0.05])
o.integrate(ts,MWPotential2014)
js= aAA(o.R(ts),o.vR(ts),o.vT(ts),o.z(ts),o.vz(ts))
```
This also works fine without `z` and `vz` if only one
```python
js= aAA(o.R(ts)[0],o.vR(ts)[0],o.vT(ts)[0])
```
But not this without specifying `z` and `vz`. This PR will fix the issue
```python
js= aAA(o.R(ts),o.vR(ts),o.vT(ts))
```
=> Fix ActionAngle eval fail for (R,vR,vT) array input

.github/workflows/build_macosx_windows_wheels.yml, .github/workflows/build_manylinux_wheels.yml, .gitignore, HISTORY.txt, doc/source/installation.rst, doc/source/reference/potential.rst, doc/source/reference/potentialnull.rst, galpy/orbit/integrateFullOrbit.py, galpy/orbit/integratePlanarOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/potential/Force.py, galpy/potential/NullPotential.py, galpy/potential/Potential.py, galpy/potential/RotateAndTiltWrapperPotential.py, galpy/potential/__init__.py, galpy/potential/potential_c_ext/RotateAndTiltWrapperPotential.c, galpy/util/conversion.py, tests/test_actionAngle.py, tests/test_orbit.py, tests/test_potential.py, tests/test_quantity.py
adds an `offset` option that allows the RotateAndTiltWrapper potential to also be offset in Cartesian coordinates, after the rotation and tilt is applied. I think the test should cover all the added code - not sure if there is sufficient testing of the offset as added to the C code, though. Will add that if necessary!
=> Include an offset option in RotateAndTiltWrapperPotential

.appveyor.yml, .github/workflows/build.yml, .github/workflows/build_windows.yml, HISTORY.txt, README.md, doc/source/installation.rst, galpy/orbit/Orbits.py, galpy/orbit/integrateFullOrbit.py, galpy/orbit/integrateLinearOrbit.py, galpy/orbit/integratePlanarOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integrateFullOrbit.h, galpy/orbit/orbit_c_ext/integrateLinearOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/util/multi.py, tests/test_quantity.py
As requested by @jmackereth _years ago_...
Example:
Not adding a progress bar for action-angle calculations at this point, because the C calculation isn't structured as a loop of the full calculation over all objects (instead, various components of the calculation are done for all objects). So it's more difficult to define 'progress'. But when there is a metric of progress, the code in this PR should make it pretty easy to implement a progress bar for action-angle calculations as well.
.
=> Add a progress bar when integrating multiple orbits at once

galpy/orbit/orbit_c_ext/integratePlanarOrbit.c
This fixes the error:
```
galpy/orbit/orbit_c_ext/integratePlanarOrbit.c:439:35: error: incompatible function pointer types assigning to 'double (*)(double, double, double, double, struct potentialArg *)' from 'double (*)(double, double, double, struct potentialArg *)' [-Wincompatible-function-pointer-types]
potentialArgs->potentialEval= &ZeroPlanarForce;
```
https://app.circleci.com/pipelines/github/hoodmane/pyodide/3785/workflows/deda3693-7508-459d-a8e1-2f576f821532/jobs/45989
=> Fix function pointer disagreement

.github/workflows/build_windows.yml
But we still need it to install the GSL. But no conda for anything else, so we can decouple the conda Python version and the test Python version. This has many advantages
=> Don't use conda for windows tests

galpy/actionAngle/actionAngleStaeckel.py, tests/test_actionAngle.py
Adds a check for z=0 in estimateDeltaStaeckel and sets to 1e-4. This figure shows that delta approaches a constant value for z->0 and setting z=1e-4 returns an appropriate value (dashed lines)
=> Fix for issue #506

doc/source/reference/df.rst, galpy/df/constantbetadf.py, galpy/df/eddingtondf.py, galpy/df/sphericaldf.py, galpy/potential/interpSphericalPotential.py, tests/test_sphericaldf.py
Adds _rforce_jax to interpSphericalPotential and a check for phi during the creation of the rphi interpolator for spherical DFs. Tests are implemented for eddingtondf and constantbetadf down to beta=-0.5. Adds warning for use of interpSphericalPotential for beta<-0.5. Adds brief note about use of interpolated potentials in spherical DFs in documentation.
=> Enable interpSphericalPotential as pot= in spherical DFs (second try)

galpy/df/sphericaldf.py, tests/test_sphericaldf.py
- Passing `rmin` as astropy quantity to `sphericaldf.sample()` always fails the comparison with `self._rmin_sampling`, so parse to internal units first.
- Uncomment the try-except sequence in `_make_cmf_interpolator()` to allow galpy potentials that don't have vectorized mass calculations to work properly.
- Add `use_physical=False` to the mass normalization for `self._rmin_sampling > 0` so it works properly when denspot has ro,vo set.
=> minor astropy units + mass calc fixes

galpy/potential/DehnenBarPotential.py, tests/test_potential.py
This currently didn't work, because the formation and steady-state times were always specified in terms of the bar period, which is infinite for zero pattern speed. Fixed by making them actual times when the pattern speed is zero.
=> Allow ``DehnenBarPotential`` to work with zero pattern speed

galpy/potential/SteadyLogSpiralPotential.py, tests/test_potential.py
This currently didn't work, because the formation and steady-state times were always specified in terms of the spiral period, which is infinite for zero pattern speed. Fixed by making them actual times when the pattern speed is zero. Equivalent of #584 but for the ``SteadyLogSpiralPotential``.
=> Allow ``SteadyLogSpiralPotential`` to work with zero pattern speed

HISTORY.txt, doc/source/orbit.rst, galpy/orbit/Orbits.py, galpy/util/conversion.py, galpy/util/coords.py, tests/test_coords.py, tests/test_orbits.py
In all cases except for lists of `Orbit` instances for now.
=> Allow vector inputs of solar parameters to `Orbit` initialization: `ro`, `zo`, `vo`, and `solarmotion`

.github/workflows/wheels.yml
Because Python 3.12 seems to be working (see `py312` branch), this PR adds wheels for Python 3.12.
=> Add Python 3.12 wheels

.github/workflows/build.yml
Because of newer ``pynbody`` versions' incompatibility with Python 3.9 (see https://github.com/pynbody/pynbody/issues/753).
=> Pin ``pynbody`` version to 1.4.2 for Python 3.8 tests

.github/workflows/build.yml
Now that the offending Python 3.8 versions were yanked from PyPI, so just pip installing pynbody again installs a Python 3.8-compatible version.
=> Simplify pynbody installation in tests again 

galpy/df/diskdf.py, galpy/df/streamgapdf.py, galpy/util/quadpack.py
Also use renamed `simpson` rather than `simps`.
=> Vendor scipy.integrate.romberg due to impending deprecation within scipy

HISTORY.txt, README.dev, doc/source/reference/potential.rst, doc/source/reference/potentialkuzminlikewrapper.rst, galpy/orbit/integrateFullOrbit.py, galpy/orbit/integratePlanarOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/potential/KuzminLikeWrapperPotential.py, galpy/potential/RotateAndTiltWrapperPotential.py, galpy/potential/__init__.py, galpy/potential/potential_c_ext/KuzminLikeWrapperPotential.c, galpy/potential/potential_c_ext/galpy_potentials.h, tests/conftest.py, tests/test_actionAngle.py, tests/test_orbit.py, tests/test_potential.py
A wrapper to turn any spherical or axisymmetric potential into a potential of Kuzmin/Miyamoto-Nagai form (Tohline & Voyages 2001; Hunter 2003, 2005).
=> Add ``KuzminLikeWrapperPotential``

.github/workflows/build.yml, .github/workflows/build_windows.yml
**This issue just tracks progress to fully changing the build/test infrastructure to Python 3.12** Python 3.12 wheels are already being created successfully and are included in the latest release. 
This PR tracks progress towards fully supporting Python 3.12. Any necessary fixes will be done separately outside of this PR, so actual Python 3.12 support can be achieved for many platforms before achieving it for all. We believe, in fact, that galpy fully works, but it is hard to fully test until all dependencies support Python 3.12. 
Current status:
- Linux works, but can't run tests dependent on ``JAX`` or ``numba``, because they do not support Python 3.12 yet. This affects only the spherical DFs (for ``JAX``) and the non-inertial-frame force tests
- Mac does not work because of an issue …
=> Add Python 3.12 support

.github/workflows/wheels.yml
Among other things, , to make sure to create the 64bit mac wheel now that [macos-latest is becoming M1](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/)
=> Set runners used in wheels workflow explicitly

.github/workflows/build.yml
Doesn't seem to be necessary currently because we are back to installing `pynbody` wheels and when building `pynbody` becomes necessary again, might have to do GCC13 anyway..
=> Remove specific gcc version for installing ``pynbody``

setup.py
Thanks @henrysky for pointing this out in #651!
=> Remove defining inline for MVSC because no longer necessary

.github/workflows/wheels.yml, setup.py
Because Python 3.13 seems to be working (see #673), this PR adds wheels for Python 3.13.
=> Add Python 3.13 wheels

galpy/df/kingdf.py, galpy/df/sphericaldf.py, galpy/potential/KingPotential.py, tests/test_potential.py, tests/test_sphericaldf.py
Fixes the fact that KingPotential was missing a constant offset to make the potential exactly Keplerian -GM/r outside the tidal radius. Also updates how the cumulative mass profile is calculated and how it is interpolated in general for spherical adds. And also updates the silver for the King profile slightly.
=> Correct behaviour of the potential in KingPotential

HISTORY.txt, galpy/actionAngle/actionAngleStaeckel.py, galpy/potential/DissipativeForce.py, galpy/potential/Potential.py, galpy/potential/linearPotential.py, galpy/potential/planarDissipativeForce.py, galpy/potential/planarPotential.py, galpy/potential/verticalPotential.py, galpy/util/symplecticode.py, tests/test_orbit.py, tests/test_potential.py
See discussions in #365
This change aligns the Python implementation of the leapfrog integrator with the C code by combining the drift calculations to reduce computations in the inner integration loop.
Also, the checks for non-axisymmetric and dissipative Potentials are moved from the internal (e.g., _evaluateRforces) to public (e.g., evaluateRforces) methods in order to avoid calling the checks at every loop iteration.
Provides a ~50% reduction in computation time.
Profiling `main` using [this script](https://gist.github.com/jamesgrimmett/0efa7638a13ffcfbc9dea424c5220e75)
```
55743016 function calls (49982710 primitive calls) in 27.938 seconds
Ordered by: cumulative time
List reduced from 99 to 50 due to restriction <50>
ncalls  tottime  percall  cumtime  percall …
```
=> Improve Python leapfrog integration performance

doc/source/potential.rst
This PR updates potential.rst to reflect changes made in pynbody (primarily the documentation and test data URLs)
It also changes the example so that it only makes use of public interface rather than protected members, and in doing so reduces the number of calls made to pynbody.
=> Update potential.rst for changes in pynbody docs/data

galpy/potential/SCFPotential.py, galpy/util/quadpack.py
We didn't need ``vectorize1`` anyway! Argh!
=> Fix scipy 1.15 deprecations: removal of ``vectorize1`` and ``lpmn`` --> ``assoc_legendre_p_all``

galpy/potential/potential_c_ext/PowerSphericalPotentialwCutoff.c
Hi @jobovy, here is the change that we discussed in (i) of #701 
For test cases, I've used integrations of the Sun over 1000Gyr (in order to get a decent sample size for profiling) and MW Globular clusters over 10Gyr;
```
ts = np.linspace(0,1000,100001)*u.Gyr
sun = Orbit()
t = time.time()
sun.integrate(ts, mw_pot, method="symplec4_c")
print(f"Duration Sun: {time.time() - t}")
ts = np.linspace(0,10,1001)*u.Gyr
o = Orbit.from_name('MW globular clusters')
t = time.time()
o.integrate(ts, mw_pot, method="symplec4_c")
print(f"Duration MW globular clusters: {time.time() - t}")
```
With the current `main` branch (using `gsl_sf_gamma_inc`), I find
```
Duration Sun: 9.844529867172241
Duration MW globular clusters: 6.79642391204834
```
and with this change (using `gsl_sf_gamma_inc_P`), I find
``` …
```
=> Swap gsl_gamma_inc with gsl_gamma_inc_P for mass calculation

HISTORY.txt, doc/source/orbit.rst, galpy/orbit/Orbits.py, galpy/orbit/integratePlanarOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/orbit/orbit_c_ext/integrateLinearOrbit.c, galpy/orbit/orbit_c_ext/integratePlanarOrbit.c, galpy/util/wez_ias15.c, galpy/util/wez_ias15.h, setup.py, tests/test_orbit.py
Implemented the ias15 algorithm in c with python wrappers, and added to relevant tests.
Some notes:
- Didnt implement the “begins to oscillate”
- Used "global" calculations.
- Didn't implement user warning for 12 iterations
- My implementation treats each step as an independant integration, with dynamic stepping in between. This part seems a bit silly but I thought at least I would give a working version at first. Otherwise, I would need to create an interpolation function to match the other integrators.
- Slight concern that it might get caught in infinite loop, in the while time remaining > 0 loop.
=> Ias15 implentation

.github/workflows/build.yml, .github/workflows/build_windows.yml, .github/workflows/wheels.yml, README.md, galpy/orbit/Orbits.py
**This issue just tracks progress to fully changing the build/test infrastructure to Python 3.13. Python 3.13 wheels were already added in #674 and are part of the latest version (since the 1.10.1 release).**
**Ready to be merged as soon as ``numba`` releases 0.61.**
This PR tracks progress towards fully supporting Python 3.13. Any necessary fixes will be done separately outside of this PR, so actual Python 3.13 support can be achieved for many platforms before achieving it for all. We believe, in fact, that galpy fully works, but it is hard to fully test until all dependencies support Python 3.13. 
Current status:
- Linux works almost 100%, but can't run tests dependent on ``JAX`` or ``numba``, because they do not support Python 3.13 yet. This affects only the spherical DFs (for ``JAX``) …
=> Add Python 3.13 support

galpy/orbit/Orbits.py, tests/test_orbit.py
Fixes #700, but more generally clarifies the use of equispaced and non-equispaced integration time arrays.
=> Clarify use of non-equispaced time arrays in orbit integration

.bumpversion.cfg, CITATION.cff, HISTORY.txt, doc/source/conf.py, galpy/__init__.py, setup.py
Update HISTORY.txt and version number.
=> Release 1.10.2

galpy/orbit/integrateFullOrbit.py, galpy/orbit/orbit_c_ext/integrateFullOrbit.c, galpy/potential/potential_c_ext/PowerSphericalPotentialwCutoff.c
Hi @jobovy, here are the second set of changes to close off https://github.com/jobovy/galpy/issues/701.
I've taken two different approaches in two commits, happy to rebase this branch to contain whichever you prefer.
In https://github.com/jobovy/galpy/commit/020eb773eb2ad2b7b7e277cf55f331927cee1827 I've implemented the caching of the mass in the `Rforce` and `zforce` functions. I left the Planar functions as-is (including the nargs/potentialArgs) because I don't think there would be any performance benefit from caching in the Planar case, but just let me know if you'd prefer the caching to be included for the Planar functions as well for consistency (or if I'm mistaken about the lack of benefit).
In https://github.com/jobovy/galpy/commit/84da14b4bd885465f86f16bf8e988729650928ff I instead …
=> Implement caching of the mass for the PowerSphericalPotentialwCutoff potential

.github/workflows/build_windows.yml
This warning is encountered somewhere in matplotlib, so is not our problem to deal with.
=> Ignore Pillow 'mode' parameter deprecation warning

galpy/util/bovy_rk.c, galpy/util/bovy_symplecticode.c, tests/test_evolveddiskdf.py, tests/test_orbit.py
`rtol` is passed to C as log(rtol), but wasn't entirely correctly used as such in the C code (but it was overall correct and the impact of this bug was very small)
=> Fix use of relative tolerance parameter in some of the C integrators
