jobovy/galpy

galpy/df_src/quasiisothermaldf.py

Added pre-factor for Gauss-Legendre integration in qdf.vmomentdensity with flexible nsigma. (Forgot it before, sorry.)

Supplementary pull request

---

galpy/potential_src/KuzminKutuzovStaeckelPotential.py
galpy/util/bovy_coords.py
nose/test_coords.py
nose/test_kuzminkutuzov.py

Added a test suite for the KKS potential class.

Test Suite for the KuzminKutuzovStaeckelPotential

---

HISTORY.txt
doc/source/reference/potential.rst
doc/source/reference/potentialplummer.rst
galpy/actionAngle_src/actionAngle_c_ext/actionAngle.c
galpy/orbit_src/integrateFullOrbit.py
galpy/orbit_src/integratePlanarOrbit.py
galpy/orbit_src/orbit_c_ext/integrateFullOrbit.c
galpy/orbit_src/orbit_c_ext/integratePlanarOrbit.c
galpy/potential.py
galpy/potential_src/PlummerPotential.py
galpy/potential_src/potential_c_ext/PlummerPotential.c
galpy/potential_src/potential_c_ext/galpy_potentials.h
nose/test_actionAngle.py
nose/test_nemo.py
nose/test_orbit.py
nose/test_potential.py

Add Plummer potential

---

HISTORY.txt
doc/source/reference/potential.rst
doc/source/reference/potentialpseudoiso.rst
galpy/actionAngle_src/actionAngle_c_ext/actionAngle.c
galpy/orbit_src/integrateFullOrbit.py
galpy/orbit_src/integratePlanarOrbit.py
galpy/orbit_src/orbit_c_ext/integrateFullOrbit.c
galpy/orbit_src/orbit_c_ext/integratePlanarOrbit.c
galpy/potential.py
galpy/potential_src/PseudoIsothermalPotential.py
galpy/potential_src/potential_c_ext/PseudoIsothermalPotential.c
galpy/potential_src/potential_c_ext/galpy_potentials.h
nose/test_actionAngle.py
nose/test_orbit.py

Add pseudo-isothermal potential

---

HISTORY.txt
doc/source/reference/potential.rst
doc/source/reference/potentialkuzmindisk.rst
galpy/orbit_src/integrateFullOrbit.py
galpy/orbit_src/integratePlanarOrbit.py
galpy/orbit_src/orbit_c_ext/integrateFullOrbit.c
galpy/orbit_src/orbit_c_ext/integratePlanarOrbit.c
galpy/potential.py
galpy/potential_src/KuzminDiskPotential.py
galpy/potential_src/potential_c_ext/KuzminDiskPotential.c
galpy/potential_src/potential_c_ext/galpy_potentials.h
nose/test_orbit.py
nose/test_potential.py

Implemented Kuzmin Disk Potential

Kuzmin Disk Potential

---

galpy/orbit_src/integratePlanarOrbit.py
galpy/potential_src/SCFPotential.py
galpy/potential_src/potential_c_ext/SCFPotential.c
nose/test_orbit.py
nose/test_potential.py

SCF Potential updated for bugs.

SCF Potential updated

---

HISTORY.txt
doc/source/reference/potentialhernquist.rst
doc/source/reference/potentialscfcompute.rst
doc/source/reference/potentialscfcomputeaxi.rst
doc/source/reference/potentialscfcomputesphere.rst
galpy/potential_src/SCFPotential.py

Added references and fixed algebraic mistakes in the documentation.
Also added SCFPotential into HISTORY.txt

Updated documentation to SCFPotential

---

.travis.yml
doc/source/reference/potential.rst
galpy/actionAngle_src/actionAngleAdiabaticGrid.py
galpy/actionAngle_src/actionAngleIsochrone.py
galpy/actionAngle_src/actionAngleIsochroneApprox.py
galpy/actionAngle_src/actionAngleStaeckel.py
galpy/actionAngle_src/actionAngleStaeckelGrid.py
galpy/df_src/quasiisothermaldf.py
galpy/df_src/streamdf.py
galpy/df_src/streamgapdf.py
galpy/orbit_src/integrateFullOrbit.py
galpy/orbit_src/integratePlanarOrbit.py
galpy/orbit_src/orbit_c_ext/integrateFullOrbit.c
galpy/orbit_src/orbit_c_ext/integratePlanarOrbit.c
galpy/potential_src/DehnenBarPotential.py
galpy/potential_src/DoubleExponentialDiskPotential.py
galpy/potential_src/SnapshotRZPotential.py
galpy/potential_src/interpRZPotential.py
galpy/potential_src/plotEscapecurve.py
galpy/potential_src/potential_c_ext/DehnenBarPotential.c
galpy/potential_src/potential_c_ext/galpy_potentials.h
tests/test_orbit.py
tests/test_potential.py
tests/test_quantity.py
tests/test_streamgapdf.py

This PR upgrades the DehnenBarPotential to 3D following [Monari et al. (2016)](http://adsabs.harvard.edu/abs/2016MNRAS.461.3835M)

3D version of DehnenBarPotential

---

AUTHORS.txt
HISTORY.txt
galpy/df/quasiisothermaldf.py
tests/test_qdf.py
tests/test_quantity.py
tests/test_streamgapdf.py

I added a sample velocity function to qdf that samples for many positions at once and is faster than the old sampleV function because it uses interpolation.

Add qdf sampleV_interpolate

---

AUTHORS.txt
HISTORY.txt
doc/source/reference/bovycoords.rst
doc/source/reference/coordscustomtopmrapmdec.rst
doc/source/reference/coordscustomtoradec.rst
galpy/util/bovy_coords.py
tests/test_coords.py

adding custom_to_radec function in bovy_coords

Customcoords

---

galpy/util/leung_dop853.c
galpy/util/leung_dop853.py

fixing issue #390: Inconsistent behaviour of dop853 when integrating from a nonzero initial time step

---

galpy/orbit/Orbits.py
tests/test_orbit.py

Hi @jobovy, just a small expansion to allowed input types.
Signed-off-by: Nathaniel Starkman (@nstarman) <nstarkman@protonmail.com>

expand Orbit init to accept tuples

---

setup.py

Upstream patches required to get ``galpy`` to work in ``pyodide``

---

HISTORY.txt
galpy/orbit/Orbits.py

and probably in the WASM package as well.

Fix use of ``animate`` and ``animate3d`` in jupyterlab and retrolab

---

.github/workflows/build.yml
.github/workflows/build_windows.yml
HISTORY.txt
galpy/actionAngle/actionAngle.py
galpy/df/constantbetaHernquistdf.py
galpy/df/df.py
galpy/df/isotropicHernquistdf.py
galpy/df/osipkovmerrittHernquistdf.py
galpy/orbit/Orbits.py
galpy/potential/Force.py
galpy/potential/linearPotential.py
galpy/potential/planarPotential.py
galpy/potential/plotEscapecurve.py
galpy/potential/plotRotcurve.py
tests/test_SpiralArmsPotential.py
tests/test_actionAngle.py
tests/test_dynamfric.py
tests/test_orbit.py
tests/test_potential.py
tests/test_sphericaldf.py

Runs tests with the following warnings turned into errors:
- DeprecationWarning
- FutureWarning
- AstropyDeprecationWarning

Run tests with deprecation warnings turned on

---

HISTORY.txt
doc/source/orbit.rst
doc/source/reference/orbit.rst
doc/source/reference/orbitbrutesos.rst
doc/source/reference/orbitplotbrutesos.rst
galpy/orbit/Orbits.py
galpy/util/plot.py
tests/test_orbit.py
tests/test_orbits.py

For cases where the specialized method doesn't work (e.g., orbits in the non-inertial frame of a rotating bar).

Add a brute-force SOS method and plotting function

---

galpy/potential/SoftenedNeedleBarPotential.py
galpy/potential/potential_c_ext/SoftenedNeedleBarPotential.c

Previously, evaluating the ``SoftenedNeedleBarPotential`` vertical force along the major axis gave NaN...

Allow ``SoftenedNeedleBarPotential`` to be evaluated properly along the major axis

---

.bumpversion.cfg
CITATION.cff
HISTORY.txt
doc/source/conf.py
doc/source/installation.rst
doc/source/orbit.rst
doc/source/potential.rst
doc/source/streamdf.rst
doc/source/whatsnew.rst
galpy/__init__.py
setup.py

Add release docs and bump version.

Prepare 1.9.0 release

---

.bumpversion.cfg
CITATION.cff
HISTORY.txt
doc/source/conf.py
galpy/__init__.py
setup.py
tests/test_sphericaldf.py

Update HISTORY, bump version, fix jax config issue in tests.

Release 1.9.1

---

.github/workflows/build_pyodide_wheels.yml
galpy/df/streamspraydf.py

Fix a bug in streamspraydf to remove the streaks.
Before this fix: 
After the fix:

Fix a bug in streamspraydf to remove the streaks.

---

galpy/potential/TwoPowerTriaxialPotential.py

I think there's a small error in the bounds of integration in the docstring.

update docs in triaxialNFW

---

galpy/potential/RotateAndTiltWrapperPotential.py
tests/test_potential.py

and test explicitly that the docs are correct

Clarify documentation of RotateAndTiltWrapper's use of galaxy/sky PA and inclination

---

.bumpversion.cfg
CITATION.cff
HISTORY.txt
doc/source/actionAngle.rst
doc/source/conf.py
doc/source/orbit.rst
doc/source/whatsnew.rst
galpy/__init__.py
setup.py

Update HISTORY.txt, docs, and version number.

Release 1.10.0

---

doc/source/_templates/layout.html
doc/source/conf.py

See https://about.readthedocs.com/blog/2024/07/addons-by-default/

Handle Readthedocs context inject deprecation

---

galpy/potential/potential_c_ext/DehnenBarPotential.c
tests/test_potential.py

Fix small bug in the C implementation of ``DehnenBarPotential``

---

.bumpversion.cfg
CITATION.cff
HISTORY.txt
doc/source/conf.py
galpy/__init__.py
setup.py

Update HISTORY.txt and version number.

Release 1.10.1

---

.github/workflows/build.yml
galpy/orbit/Orbits.py
galpy/util/_optional_deps.py

Necessary because of astropy/astroquery#2954.

Support new ``astroquery`` Simbad API in ``Orbit.from_name``

---

galpy/actionAngle/actionAngleStaeckel.py
galpy/orbit/Orbits.py
galpy/potential/AnySphericalPotential.py
tests/test_actionAngle.py

Fix handling of unbound orbits in the action-angle orbit interface.

---

galpy/orbit/Orbits.py
tests/test_orbit.py

Print warning when initializing an Orbit with a SkyCoord that does not have the Sun's positional and velocity parameters set
